#!/bin/bash
rm -r dist >> /dev/null
mkdir dist >> /dev/null
mkdir dist/config >> /dev/null
printf "Compiling layout..."
javac\
    -d dist\
    -Xlint\
    -Xlint:-serial\
    -classpath dist\
    layout/*.java
printf "\rCompiling label..."
javac\
	-d dist\
	-Xlint\
	-Xlint:-serial\
	-classpath dist\
	label/*.java
cp config/* dist/config
printf "\rDone.               \n"
