#!/bin/bash
rm -r dist >> /dev/null
mkdir dist >> /dev/null
mkdir dist/config >> /dev/null
printf "\rCompiling..."
javac\
  -d dist\
  -Xlint\
  -Xlint:-serial\
  -classpath dist\
  config/*.java label/*.java layout/*.java
cp config/*.xml config/*.dtd dist/config
printf "\rDone.               \n"
